package io.github.HollowKnight.Controller;

public enum GameEvent {
    // Knight movement
    KNIGHT_JUMPED,
    KNIGHT_DOUBLE_JUMPED,
    KNIGHT_WALL_JUMPED,
    KNIGHT_DASHED,
    KNIGHT_LANDED,

    // Knight combat
    KNIGHT_ATTACKED,
    KNIGHT_HIT_ENEMY,
    KNIGHT_GAINED_SOUL,
    KNIGHT_CAST_SPELL,
    KNIGHT_HEALED,
    KNIGHT_TOOK_DAMAGE,
    KNIGHT_HIT_HAZARD,
    KNIGHT_DIED,

    // Spells
    VENGEFUL_SPIRIT_CAST,
    HOWLING_WRAITHS_CAST,

    // World
    ENEMY_DIED,
    BOSS_SPAWNED,
    BOSS_FIGHT_STARTED,
    BOSS_STUNNED,
    BOSS_PHASE2,
    BOSS_PHASE_CHANGE,
    BOSS_DEFEATED,
    BOSS_HEAVY_IMPACT,
    FALSE_KNIGHT_DEFEATED,
    ENEMY_KILLED,
    ROOM_ENTERED,
    GAME_FINISHED,
    BREAKABLE_WALL_HIT,
    BREAKABLE_WALL_DESTROYED,
    ROOM_TRANSITION,

    // UI triggers
    ACHIEVEMENT_UNLOCKED,
    CHARM_EQUIPPED,
    CHARM_UNEQUIPPED,
    GAME_SAVED,
    GAME_LOADED,
    CHEAT_ACTIVATED,
    CHEAT_BOSS_TELEPORT
}
